python ../src/excel_and_json.py singlebook -o ./ -i GlobalConfig.xlsx
python ../src/excel_and_json.py singlebook -o ./ -i Weapons.xlsx
python ../src/excel_and_json.py singlebook -o ./ -i WeaponAdds.xlsx
python ../src/excel_and_json.py singlebook -o ./ -i WeaponAttributes.xlsx
python ../src/excel_and_json.py singlebook -o ./ -i WeaponFrames.xlsx
python ../src/excel_and_json.py singlebook -o ./ -i WeaponImpacts.xlsx
python ../src/excel_and_json.py singlebook -o ./ -i Roles.xlsx
python ../src/excel_and_json.py singlebook -o ./ -i RoleAttributes.xlsx
python ../src/excel_and_json.py singlebook -o ./ -i LevelMonsters.xlsx
python ../src/excel_and_json.py singlebook -o ./ -i Monsters.xlsx
python ../src/excel_and_json.py singlebook -o ./ -i Animations.xlsx
python ../src/excel_and_json.py singlebook -o ./ -i Transits.xlsx
python ../src/excel_and_json.py singlebook -o ./ -i Assaults.xlsx
